export enum UserErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_ROLE = 'INVALID_ROLE',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',
  AVATAR_TOO_LARGE = 'AVATAR_TOO_LARGE',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  NAME_REQUIRED = 'NAME_REQUIRED',
}
